name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          submodules: true

      - name: Update submodules
        run: git submodule update --remote

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: _site
