name: Import Data from Sirius
on:
  schedule:
    - cron: "0 7 * * 1-5"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Pull Sirius Source data
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
        run: |
          gh run download -n data-dictionary-json  -R ministryofjustice/opg-sirius -D /tmp/sirius_tables/
          cp /tmp/sirius_tables/* ./src/_data/sirius_tables/

      - name: Create a signed commit
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@94f69f8b54a572761f1dfb8d723ba7b71b3f671a # v6.1.1
        with:
          github_token: ${{ secrets.ORG_ACCESS_TOKEN }}
          pr_title: "Data tables update"
          pr_body: "Updating tables for data from Sirius tables"
