name: Test Build
on:
  push:
    branches-ignore: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2.3.1

      # - name: Install and Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Pull source data
        env:
          GITHUB_TOKEN:  ${{ secrets.ORG_ACCESS_TOKEN }}
        run: |
          gh run download -n data-dictionary-json  -R ministryofjustice/opg-sirius
          ls -la 
