name: Test Build
on:
  push:
    branches-ignore:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          submodules: true

      - name: Install and Build
        run: |
          npm install
          npm run build
