name: Test Build
on:
  push:
    branches-ignore: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Pull source data
        uses: actions/download-artifact@v3
        with:
          github_token: ${{secrets.ORG_ACCESS_TOKEN}}
          repo: ministryofjustice/opg-sirius
          branch: master
          name: data-dictionary-json
          search_artifacts: true

      - name: Display structure of downloaded files
        run: ls -R
