name: Test Build
on:
  push:
    branches-ignore: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Pull source data
        uses: dawidd6/action-download-artifact@v2
        with:
          #github_token: ${{secrets.GITHUB_TOKEN}}
          repo: ministryofjustice/opg-sirius
          branch: master
          name: data-dictionary-json
          search_artifacts: true
          path: ./
